import { LeadInput } from "./types";

/** Beispiel-Leads zum Ausprobieren des Dashboards (echte Domains, Daten fiktiv). */
export const SEED_LEADS: LeadInput[] = [
  {
    name: "Trattoria Bella Napoli",
    company: "Bella Napoli GmbH",
    source: "google_maps",
    industry: "Restaurant / Gastro",
    city: "München",
    country: "DE",
    website: "example.com",
    phone: "+49 89 1234567",
    notes: "Hohe Bewertung, viele Anfragen über Telefon – Reservierungs-Bot ideal.",
  },
  {
    name: "Dr. Sarah Wagner",
    company: "Zahnarztpraxis Wagner",
    source: "google_maps",
    industry: "Zahnarzt / Praxis",
    city: "Hamburg",
    country: "DE",
    website: "example.org",
    email: "praxis@example.org",
    notes: "Nur Kontaktformular, keine schnelle Erreichbarkeit.",
  },
  {
    name: "FitZone Studio",
    company: "FitZone Berlin",
    source: "instagram",
    industry: "Fitness / Studio",
    city: "Berlin",
    country: "DE",
    instagram: "@fitzone.berlin",
    website: "iana.org",
    notes: "Viele DMs auf Insta, kein automatisierter Antwortbot.",
  },
  {
    name: "Lukas Brandt",
    company: "Brandt Immobilien",
    source: "linkedin",
    industry: "Immobilien / Makler",
    city: "Köln",
    country: "DE",
    linkedin: "linkedin.com/in/lukas-brandt",
    email: "kontakt@brandt-immobilien.example",
    notes: "Entscheider, skaliert gerade – guter Pitch für Lead-Qualifizierungs-Bot.",
  },
  {
    name: "Café Sonnenschein",
    source: "google_maps",
    industry: "Café / Gastro",
    city: "Stuttgart",
    country: "DE",
    phone: "+49 711 998877",
    notes: "Keine Website gefunden – evtl. erst Online-Präsenz nötig.",
  },
  {
    name: "Glow Beauty Lounge",
    company: "Glow Kosmetikstudio",
    source: "instagram",
    industry: "Beauty / Kosmetik",
    city: "Düsseldorf",
    country: "DE",
    instagram: "@glow.beauty.lounge",
    website: "example.net",
    notes: "Terminbuchung läuft chaotisch über DMs.",
  },
];
